// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProLearnDB.Data;

#nullable disable

namespace ProLearnDB.Migrations
{
    [DbContext(typeof(ProLearnDBContext))]
    partial class ProLearnDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProLearnDB.Models.CorrectAnswer", b =>
                {
                    b.Property<int>("CorrectAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CorrectAnswerId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CorrectAnswerId");

                    b.ToTable("CorrectAnswers");
                });

            modelBuilder.Entity("ProLearnDB.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CorrectAnswerId")
                        .HasColumnType("integer");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueChoice1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueChoice2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueChoice3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TestTitleId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex("CorrectAnswerId");

                    b.HasIndex("TestTitleId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ProLearnDB.Models.TestTitle", b =>
                {
                    b.Property<int>("TestTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestTitleId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TestTitleId");

                    b.ToTable("TestTitles");
                });

            modelBuilder.Entity("ProLearnDB.Models.Question", b =>
                {
                    b.HasOne("ProLearnDB.Models.CorrectAnswer", "CorrectAnswer")
                        .WithMany("Questions")
                        .HasForeignKey("CorrectAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProLearnDB.Models.TestTitle", "TestTitle")
                        .WithMany("Questions")
                        .HasForeignKey("TestTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorrectAnswer");

                    b.Navigation("TestTitle");
                });

            modelBuilder.Entity("ProLearnDB.Models.CorrectAnswer", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ProLearnDB.Models.TestTitle", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
